name: smart_farm
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^8.1.0
  fl_chart: ^0.36.0
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  get: ^4.1.4
  signale:
    git: https://github.com/Nightmare-MY/signale
  # svg图像
  flutter_svg: ^0.19.3
  # Flutter新开放的共享元素动画
  animations: ^1.0.0+5

  # 屏幕适配
  flutter_screenutil: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
